name: Release Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

env:
  node-version-file: ".nvmrc"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/init-all
        with:
          node-version-file: ${{ env.node-version-file }}
          protoc: false

      - name: Version packages
        run: yarn new-version ${{ github.event.inputs.version }} --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
