name: Create New Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      force-publish:
        description: 'Force publish even if there are no changes'
        required: false
        default: false
        type: boolean

env:
  node-version-file: ".nvmrc"

jobs:
  new-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false
          fetch-depth: 0

      - uses: ./.github/actions/init-all
        with:
          node-version-file: ${{ env.node-version-file }}
          protoc: false

      - name: Version packages
        run: yarn new-version --yes ${{ github.event.inputs.force-publish && '--force-publish' }} ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
